### ISSUE TITLE
Feature request: Nuget package

### ISSUE THREAD

**Issue by nzbart** [JDanielSmith/StringComparisonString#1]
This looks like an interesting project that might solve a problem we currently have. Is there any chance of you adding a licence file and publishing on Nuget?

**Comment by JDanielSmith** [comment]
Happy to add a license (do whatever you want with the code), no plans to publish on Nuget.

**Comment by JDanielSmith** [comment]
MIT license added.

**Comment by nzbart** [comment]
Thanks, @JDanielSmith.
